# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b308285a608b783e6689e0cc71b30e421edf134ee4fbbcc871785621acb96ce77a4a1baa0785c2c8430f7da1c9b99998813e4aabab40cfb27eda93b128e5808

test:
  secret_key_base: aa0465e849466d0e3849f4d2c2749d0f136f2f155a2b219f1fc91dc77c65bb8d8838df6ac7adb32a23920753856911f81c8b66bca9a68c5be28baed1fa0da4a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
